version = 0.1
[default.deploy.parameters]
stack_name = "infra-admin-api"
resolve_s3 = true
s3_prefix = "infra-admin-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
tags = "project=\"infra-admin-api\" techlead=\"pc42@illinois.edu\""