AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for DynamoDB Table
Transform: AWS::Serverless-2016-10-31

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: infra-admin-api
      AttributeDefinitions:
        - AttributeName: netid
          AttributeType: S
      KeySchema:
        - AttributeName: netid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  create_user:
    Type: AWS::Lambda::Function
    Properties:
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code: 
        S3Bucket: #???
        S3Key: #???
        ZipFile: backend/create_user.py
      Timeout: 5
    #Before adding more functions, it would be helpful to know what properties the function should have

Outputs:
  DynamoDBTableName:
    Description: The name of the DynamoDB table
    Value: !Ref MyDynamoDBTable
