AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for DynamoDB Table
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Description: Environment
    Type: String
    AllowedValues: [ 'dev', 'prod' ]

  AlertSNSArn:
    Description: SNS Queue to send alarm alerts to
    Type: String
    Default: arn:aws:sns:us-east-1:298118738376:infra-monitor-alerts

  UseCustomDomainName:
    Type: String
    Default: true
    AllowedValues: [ true, false ]

  UserManagementLambdaName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: infra-admin-api-user-management-lambda


Conditions:
  UseCustomDomainNameCond: !Equals [!Ref UseCustomDomainName, true]
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: infra-admin-api
      AttributeDefinitions:
        - AttributeName: netid
          AttributeType: S
      KeySchema:
        - AttributeName: netid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  AdminAPIUserManagementLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/user_funs.py 
      AutoPublishAlias: live
      Runtime: python3.10
      Description: User Management Lambda
      FunctionName: !Ref UserManagementLambdaName
      Handler: lambda_handler
      MemorySize: 2048
      Role: !GetAtt AdminAPIUserManagementLambdaIAMRole.Arn
      Timeout: 5

  AdminAPIUserManagementLambdaFunctionErrorAlarm:
    Type: 'AWS::Cloudwatch::Alarm'
    Condition: IsProd
    Properties: 
      AlarmName: !Sub '${UserManagementLambdaName}-alarm'
      AlarmDescription: !Sub 'Alarm if ${UserManagementLambdaName} function errors are detected.'
      Namespace: 'AWS/Lambda'
      MetricName: 'Errors'
      Statistic: 'Sum'
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: 'GreaterThanThreshold'
      Threshold: '0'
      AlarmActions:
        - !Ref AlertSNSArn
      Dimensions:
        - Name: 'FunctionName'
          Value: !Ref AdminAPIUserManagementLambda
  
  AdminAPIUserManagementLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${UserManagementLambdaName}:*
          PolicyName: lambda
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Effect: Allow
                Resource:
                  - !GetAtt MyDynamoDBTable.Arn
          PolicyName: lambda-dynamo


Outputs:
  DynamoDBTableName:
    Description: The name of the DynamoDB table
    Value: !Ref MyDynamoDBTable
