name: Node.js GHP build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'admin-api-frontend'
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - run: npm ci
      working-directory: 'admin-api-frontend'
    - run: npm run build --if-present
      working-directory: 'admin-api-frontend'
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: "admin-api-frontend/build/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    permissions:
      contents: read
      pages: write
      id-token: write
